name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - name: Extract Chrome Version
        id: extract_version
        run: echo "chrome-version=$(awk -F':' '/FROM selenium\/standalone-chrome:/ {print $2}' Dockerfile)" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image to GHCR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/nakanishi123/quitable-standalone-chrome:${{ steps.extract_version.outputs.chrome-version }} 
            ghcr.io/nakanishi123/quitable-standalone-chrome:latest
